{"ts":1352899587256,"silentsave":true,"restoring":false,"patch":[[{"diffs":[[1,"\n/**\n * Test dependencies.\n */\n\nvar start = require('./common')\n  , assert =require('assert')\n  , mongoose = start.mongoose\n\ndescribe('document: throws:', function(){\n  it('test document throws mode fails with extra fields', function () {\n    var db = mongoose.createConnection(\"mongodb://localhost/test-crash\");\n\n    // Simple schema with throws option\n    var FooSchema = new mongoose.Schema({\n        name: { type: String }\n    }, {strict: \"throw\"});\n\n    // Create the model\n    var Foo = db.model('Foo', FooSchema);\n\n    // This one shouldn't cause problems.\n    var good = new Foo({name: 'bar'});\n\n    try {\n      // The extra baz field should throw and error.\n      var bad = new Foo({name: 'bar', baz: 'bam'});\n      throw new Error(\"Document did not throw with extra fields.\");\n    } catch (e) {\n      // Make sure the error is the one we are expecting.\n      assert.equal(e.message, \"Field `baz` is not in schema.\");\n    }\n\n    db.close();\n\n  });\n})\n"]],"start1":0,"start2":0,"length1":0,"length2":960}]],"length":960}
